- .storybook/preview.module.scss
- .storybook/preview.tsx
- src/App.module.scss
- src/App.tsx
- src/components/ui/BaseButton/BaseButton.module.scss
- src/components/ui/BaseButton/BaseButton.tsx
- src/components/ui/BaseButton/BaseButton.types.ts
- src/components/ui/Button/Button.module.scss
- src/components/ui/Button/Button.stories.tsx
- src/components/ui/Button/Button.tsx
- src/components/ui/Button/Button.types.ts
- src/components/ui/Icon/Icon.module.scss
- src/components/ui/Icon/Icon.stories.tsx
- src/components/ui/Icon/Icon.tsx
- src/components/ui/IconButton/IconButton.module.scss
- src/components/ui/IconButton/IconButton.stories.tsx
- src/components/ui/IconButton/IconButton.tsx
- src/components/ui/IconButton/IconButton.types.ts
- src/main.tsx
- src/styles/_mixins.scss
- src/styles/_variables.scss
- src/styles/global.scss
- src/styles/reset.scss
- tsconfig.json
- vite.config.ts
- [https://github.com/Nexters/misik-web/issues/9](https://github.com/Nexters/misik-web/issues/9)
버튼 컴포넌트 제작
Button, IconButton 컴포넌트 제작 완료
BaseButton은 위 버튼에 기본 틀로 생각하면 될 거 같고 직접적인 UI 컴포넌트는 아니야 (확장성 고려)
구성은 radix ui 오픈 소스랑 비슷해서 좀 더 프로페셔널(?)한 코드를 원한다면 오픈 소스 코드 한번 보면 좀 더 이해하기 쉬울 거 같아
storybook은 좀 더 확인하기 편하라고 미리 추가했는데 storybook docs나 test code 작성은 좀 이후에 작업할 예정이야
버튼은 종류별로 primary, secondary, disabled
아이콘 버튼은 사이즈별로 md, sm으로 나눠봤는데 더 좋은 의견 있으면 얘기 부탁해!
참고로 버튼 width들은 따로 지정 안했는데 버튼의 width를 지정하기보다 버튼 부모 컴포넌트의 width를 지정해서 작업하는게 나을 거 같아서 버튼 width들은 다 100% 기준이야. 어차피 버튼 크기가 고정이 아니라 반응형으로 달라지는게 더 좋을 거 같아서!
추가적으로 global.scss도 추가해줬어. 원래 reset.scss에 있다가 이후 설정 확장성을 고려해서 global.scss로 따로 뺏어
global 스타일들은 내 임의대로 지정했는데 혹시 의견 있으면 얘기해줘!
- 누락된 버튼이나 추가해야할 버튼 있는지
- storybook에 잘 보이는지
- global 스타일 수정 or 개선점
- 이외 추가 의견
> [Feat/#9] 버튼 컴포넌트 제작

- src/App.module.scss
- src/App.tsx
- src/components/ui/Button/Button.module.scss
- src/components/ui/IconButton/IconButton.module.scss
- src/components/ui/Text/Text.module.scss
- src/components/ui/Text/Text.stories.tsx
- src/components/ui/Text/Text.tsx
- src/components/ui/Text/Text.types.ts
- src/styles/_variables.scss
- [https://github.com/Nexters/misik-web/issues/11](https://github.com/Nexters/misik-web/issues/11)
텍스트 컴포넌트 제작
매번 mixin 사용해서 스타일링 하는거 보다 Text 컴포넌트를 만들고 props로 스타일링 받는게 통일성 밎 확장성에 도움 될 거 같아서 만들어봤어
props들만 간단히 설명해줄게
size -> font size
color -> font color
weight -> font weight
align -> text align
위 props들은 보면 다 알 수 있을거야
truncated -> 얘는 텍스트 line clamp 및 overflow ellipsis 처리 용인데 우선은 true로 줄때 1줄 처리, 2로 넘기면 2줄 처리까지만 해놨어 이후에 필요성이 생기면 확장해볼게
내가 놓치지 않았다면 이 컴포넌트로 지금까지 나온 디자인의 텍스트들은 다 처리가 가능할꺼야. 혹시 놓친 부분이 있거나 의견 있으면 애기해줘!
- 해당 컴포넌트로 처리 불가능한 텍스트 디자인 없는지
- 이해 안가는 부분 있는지
- 이외 추가 의견
.
> [Feat/#11] 텍스트 컴포넌트 제작

- src/components/Home/Home.tsx
- src/components/ui/Input/Input.module.scss
- src/components/ui/Input/Input.stories.tsx
- src/components/ui/Input/Input.tsx
- src/components/ui/Input/Input.types.ts
- src/styles/_variables.scss
- [https://github.com/Nexters/misik-web/issues/15](https://github.com/Nexters/misik-web/issues/15)
Input 컴포넌트 제작
우선 varaint를 2종류로만 제작했는데 primary는 수정 버튼이 있는 input이고 secondary는 sheet에 있는 input이야
label이랑 length text, validation 처리 등 추가할 부분이 있기는 한데 이걸 바로 모듈화 시키는건 좀 부담일 거 같아서 해당 작업들은 뷰랑 같이 개발하면서 만들어보고 이후에 좀 모듈화 시킬 거 같아.
결국 내부 기능은 현재 focus in out에 따라서 스타일링만 구현된거고, 이외 input ui만 작업했다고 보면 될 거 같아
이후 작업은 각각의 view들 작업 하면서 추가하는 방향으로 해볼게
- input 코드 개선점
- 스토리북 개선점
- 이외 추가 의견
> [Feat/#15] Input 컴포넌트 제작

- src/components/Home/Home.tsx
- src/components/RecognitionFail/RecognitionFail.tsx
- src/components/ui/Input/Input.module.scss
- src/components/ui/Text/Text.module.scss
- src/components/ui/Text/Text.stories.tsx
- src/components/ui/Text/Text.tsx
- src/components/ui/Text/Text.types.ts
- src/styles/_mixins.scss
- src/styles/_variables.scss
- [https://github.com/Nexters/misik-web/issues/20](https://github.com/Nexters/misik-web/issues/20)
font-size token 네임 변경
기존 font-size token 이름은 내 임의대로 지었는데 그냥 사이즈 number 값으로 통일해서 변경했어
그리고 Text 컴포넌트 props도 size, weight 없애고 varaint로 통일해서 딱 디자인 시스템에 있는 typography로만 쓸 수 있게 수정했어!
이 변경점에 맞춰서 스토리북도 변경했으니까 확인해보면 될 거 같아~~
- token name 관련 의견
- 이외 스타일링 개선점이나 의견
.
> [Feat/#20] Typography 토큰 변경

- src/components/ReceiptEdit/ReceiptEdit.module.scss
- src/components/ReceiptEdit/ReceiptEdit.tsx
- src/components/ui/Input/Input.module.scss
- src/components/ui/Input/Input.tsx
- src/components/ui/Input/Input.types.ts
- src/hooks/common/useFocus.ts
- src/pages/ReceiptEditPage.tsx
- src/router/AppRouter.tsx
- [https://github.com/Nexters/misik-web/issues/22](https://github.com/Nexters/misik-web/issues/22)
영수증 인식 정보 수정 UI 제작
ui랑 일부 기능들만 구성했는데 이후에 좀 바뀔 부분들이 있을 수도 있을 거 같아
우선 이전에 논의했던게 이 페이지에서 오는 정보가 꼭 가게명, 음식명이 아닌 경우도 있을 거라 했거든? 그래서 이 부분에 대한 정책이 확정나면
컴포넌트 렌더링 방식이나 로직이 좀 변경 될 여지가 있어
그리고 focus 로직은 현재 방식이 최선인 거 같아서 일단 구성을 했는데, 이 input의 경우 primary variant만 해당되는 내용인데 input 밖으로\
div 박스가 하나 덮고 있는데 focus시 border가 div 전체가 바뀌어야 해서 input에서 기본적으로 제공하는 focus 로직을 못쓰겠더라구?
그래서 state로 관리하는 방식으로 구성했는데 혹시 더 좋은 의견이나 개선점 있으면 얘기해줘!
그리고 Title 부분도 디자인 정책상 원하는게 가게 이름에 말줄임표를 원하는 거 같아서 Text 컴포넌트를 분리해서 구성할 수 밖에 없었는데 이거도 더 좋은 방법이 있으면 얘기해줘!
수정 시 키보드가 올라오고 위에 버튼도 정상적으로 올라오는지는 이후에 네이티브에서 다시 확인을 해봐야 할 거 같아~~
전체적으로 컴포넌트를 좀 더 분리해서 렌더링 최적화도 할 수 있겠지만 이건 이후에 api 연결되고 data 가공 과정에서 한번 더 리팩토링 할 생각이야 우선은 UI 요구사항에 맞춰놓은 상태인거로 이해하면 될 거 같아 …
> [Feat/#22] 영수증 인식 정보 수정 UI 제작

- src/components/ui/Tag/Tag.module.scss
- src/components/ui/Tag/Tag.stories.tsx
- src/components/ui/Tag/Tag.tsx
- src/components/ui/Tag/Tag.types.ts
- [https://github.com/Nexters/misik-web/issues/24](https://github.com/Nexters/misik-web/issues/24)
Tag 컴포넌트 제작
현재 디자인 상에서는 해시태그 선택 페이지에서만 해당되는 컴포넌트이지만 이후 더 추가될 수 있을 거 같고 아니더라도 Button 컴포넌트와는 차별점을 두기 위해서 Tag 컴포넌트를 만들어 봤어
일반적인 태그 primary variant랑, 아이콘 버튼 태그인 add variant로 나눠서 제작했고 선택 태그의 경우 isSelect props로 구분을 줬으니 확인해보면 될 거 같아
동일하게 스토리북도!
- 태그 컴포넌트 의견, 개선점
- 스토리북 잘 보이는지
> [Feat/#24] Tag 컴포넌트 제작

- src/components/SelectTag/SelectTag.module.scss
- src/components/SelectTag/SelectTag.tsx
- src/pages/SelectTagPage.tsx
- src/router/AppRouter.tsx
- [https://github.com/Nexters/misik-web/issues/25](https://github.com/Nexters/misik-web/issues/25)
해시태그 선택 페이지 ui 제작
페이지 UI랑 태그 선택, 복수 선택 기능까지 구현한 상태야
+버튼 클릭 시 팝업 시트는 다음 브랜치에서 구현 예정이고, tag list 데이터는 임시용이라 UT 이후에 아마 바뀌지 않을까 싶네
페이지 UI는 /select-tag에서 확인 가능해!
- 로직 개선점
- 이외 의견이나 피드백
> [Feat/#25] 해시태그 선택 페이지 UI 제작

- .storybook/preview-head.html
- index.html
- src/components/Home/Home.tsx
- src/components/HomeNavigateConfirmModal/HomeNavigateConfirmModal.module.scss
- src/components/HomeNavigateConfirmModal/HomeNavigateConfirmModal.stories.tsx
- src/components/HomeNavigateConfirmModal/HomeNavigateConfirmModal.tsx
- src/components/ui/Modal/Modal.module.scss
- src/components/ui/Modal/Modal.tsx
- src/components/ui/Modal/Portal.tsx
- src/hooks/common/useOverlay.ts
- [https://github.com/Nexters/misik-web/issues/40](https://github.com/Nexters/misik-web/issues/40)
공통 모달 컴포넌트 제작
홈 이동 안내 팝업 모달 제작
우선 modal은 createPortal 사용해서 제작했어. createPortal에 elementId를 따로 추가한 이유는 modal말고 toast 메시지의 확장성이 생길 거 같아서 그때는 toast도 동일하게 portal을 사용할 예정이라 추가해줬어 (토스트 메시지 디자인 시안에 있더라구 웹에서 구현할지는 아직 미정)
그리고 지금은 home 컴포넌트에 갤러리 버튼에 modal을 붙여놨는데 이후에 리뷰 생성 완료 페이지 완성하면 거기로 옮기면 될 거 같아
테스트용으로는 여기다 유지해놓을게
/ 경로에서 갤러리 버튼 클릭하면 모달 확인 가능해
추가적으로 모달 컴포넌트 이름이 좀 마음에 안드는데.. 혹시 좋은 의견 있으면 얘기해줘! 아무리 생각해봐도 더 좋은 이름이 생각 안나더라..
(아이콘 이슈로 #34 코드를 pull해와서 #34 머지 이후에 rebase하고 머지 예정!)
- 모달 로직 개선이나 의견
- 모달 컴포넌트 이름 의견
- 이외 피드백이나 추가 의견
> [Feat/#40] 홈 이동 안내 팝업 모달 제작

- src/components/SelectTag/SelectTag.tsx
- src/components/SelectTag/TagSheet/TagSheet.tsx
- [GITHUB ISSUE LINK](#47 )
<br> 태그 추가 시트에서 태그 추가할 수 있도록 함
바깥쪽 눌러도 꺼지도록 나중에 모달 작업할 때 같이 해야할 것 같고 
혹시 뒤로가기 눌렀을 때 선택한 태그, 추가한 태그 남아있으려면 전역 상태로 관리해야 할 것 같은데 이건 2차때 해도 될 거 같으!
<br>
코드 개선점
<br>
<br>
> [Feature/#47] 태그 생성 기능 추가

- src/components/ReviewResult/ReviewResult.module.scss
- src/components/ReviewResult/ReviewResult.tsx
- src/components/ui/Toast/Toast.module.scss
- src/components/ui/Toast/Toast.stories.tsx
- src/components/ui/Toast/Toast.tsx
- src/hooks/common/useToast.ts
- src/pages/ReviewResultPage.tsx
- [GITHUB ISSUE LINK](#42 )
토스트 메세지 훅과 리뷰 생성 결과 페이지에 연결했어용
<br> 
애니메이션은 2차 mvp에 추가해야 할 것 같아 안넣었고
텍스트 복사 기능 추가했으<br>
코드 개선점
toast에 더 넣어야 할 속성이 있을지
<br>
<br>
> [Feat/#42] 토스트 컴포넌트 구현 및 연동

- src/components/Home/Home.tsx
- src/components/ReceiptEdit/ReceiptEdit.tsx
- src/components/provider/AppBridgeProvider/convertToNativeMessage.ts
- src/components/provider/WebBridgeProvider/WebBridgeProvider.tsx
- src/store/useScanDataStore.ts
- src/types/global.d.ts
> [Feat/#63] 네이티브 영수증 인식 결과, 리뷰 생성 결과 핸들러 로직 추가

- src/components/Home/Home.tsx
- src/components/provider/WebBridgeProvider/WebBridgeProvider.tsx
- [GITHUB ISSUE LINK]()
<br>
<br>
<br>
<br>
> feat: test

- src/components/Home/Home.tsx
> refactor: data field 수정

- src/components/Home/Home.tsx
- src/components/ReceiptEdit/ReceiptEdit.tsx
- src/components/provider/AppBridgeProvider/AppBridgeProvider.tsx
- [https://github.com/Nexters/misik-web/issues/79](https://github.com/Nexters/misik-web/issues/79)
영수증, 갤러리 ocr 인식 적용
.
.
.
> [Refactor/#79] 영수증, 갤러리 ocr 인식 수정

- src/components/HomeNavigateConfirmModal/HomeNavigateConfirmModal.tsx
- src/components/ReceiptEdit/ReceiptEdit.tsx
- src/components/ReviewResult/ReviewResult.tsx
- src/components/SelectStyle/SelectStyle.tsx
- src/components/provider/AppBridgeProvider/AppBridgeProvider.tsx
- src/components/provider/AppBridgeProvider/convertToNativeMessage.ts
- src/hooks/common/useRoute.ts
- src/store/useGenerateReviewStore.ts
- src/store/useReviewStore.ts
- src/store/useScanDataStore.ts
- src/types/global.d.ts
- [https://github.com/Nexters/misik-web/issues/81](https://github.com/Nexters/misik-web/issues/81)
리뷰 생성 핸들러 연결
이외 핸들러 타입 수정
.
.
.
> [Feat/#81] 리뷰 생성 핸들러 연결

- src/components/HomeNavigateConfirmModal/HomeNavigateConfirmModal.stories.tsx
- src/components/HomeNavigateConfirmModal/HomeNavigateConfirmModal.tsx
- src/components/SelectTag/TagSheet/TagSheet.tsx
- src/components/ui/Modal/Modal.tsx
- src/hooks/common/useClickOutside.ts
- [GITHUB ISSUE LINK](#51)
<br> 홈이동 모달/ 태그 추가 다이얼로그에 연결
<br> useClickOutside 훅 추가
<br> 코드 개선점 있는지
<br>
> [Feat/#51] useClickOutside 훅 구현 및 추가

- src/components/Home/Home.module.scss
- src/components/Home/Home.tsx
- src/components/HomeNavigateConfirmModal/HomeNavigateConfirmModal.module.scss
- src/components/ReceiptEdit/ReceiptEdit.tsx
- src/components/ReviewResult/ReviewResult.module.scss
- src/components/SelectStyle/SelectStyle.tsx
- src/components/SelectTag/SelectTag.module.scss
- src/components/SelectTag/SelectTag.tsx
- src/components/SelectTag/TagSheet/TagSheet.module.scss
- src/components/SelectTag/TagSheet/TagSheet.tsx
- src/components/common/Navbar/Navbar.module.scss
- src/components/common/Navbar/Navbar.tsx
- src/components/ui/IconButton/IconButton.module.scss
- src/components/ui/Input/Input.module.scss
- src/components/ui/Input/Input.tsx
- src/components/ui/Text/Text.module.scss
- src/components/ui/Text/Text.types.ts
- src/components/ui/Toast/Toast.module.scss
- src/pages/HomePage.tsx
- src/pages/ReceiptEditPage.tsx
- src/pages/ReviewResultPage.tsx
- src/styles/_variables.scss
- src/styles/global.scss
> [Refactor/#83] 디자인 QA 사항 반영

- src/components/Home/Home.tsx
- src/components/ReceiptEdit/ReceiptEdit.tsx
- src/components/provider/AppBridgeProvider/AppBridgeMessage.types.ts
- src/components/provider/AppBridgeProvider/AppBridgeProvider.tsx
- src/components/provider/AppBridgeProvider/convertToNativeMessage.ts
- src/pages/ReceiptEditPage.tsx
- src/store/useScanDataStore.ts
- src/types/global.d.ts
> [Refactor/#84] 네이티브 핸들러 타입 수정

- src/components/Home/Home.tsx
- src/components/ReceiptEdit/ReceiptEdit.tsx
- src/components/provider/AppBridgeProvider/AppBridgeMessage.types.ts
- src/components/provider/AppBridgeProvider/AppBridgeProvider.tsx
- src/components/provider/AppBridgeProvider/convertToNativeMessage.ts
- src/store/useScanDataStore.ts
- src/types/global.d.ts
> [Refactor/#84] 일부 디자인 수정, 타입 변경

- src/components/ReceiptEdit/ReceiptEdit.tsx
- src/components/RecognitionFail/RecognitionFail.tsx
- src/components/SelectTag/SelectTag.tsx
- src/constants/path.ts
- src/hooks/common/useRoute.ts
- src/pages/ReceiptInputPage/ReceiptInputPage.module.scss
- src/pages/ReceiptInputPage/ReceiptInputPage.tsx
- src/pages/ReviewResultPage/ReviewResultPage.tsx
- src/router/AppRouter.tsx
- src/store/useReviewStore.ts
> [Refactor/#94] 영수증 정보 직접 입력 페이지 수정

- src/components/provider/AppBridgeProvider/AppBridgeMessage.types.ts
- src/components/provider/AppBridgeProvider/convertToNativeMessage.ts
- src/pages/HomePage.tsx
- src/types/global.d.ts
- [https://github.com/Nexters/misik-web/issues/100](https://github.com/Nexters/misik-web/issues/100)
- 공유 텍스트 생성
- 핸들러 파라미터 수정
> [Refactor/#100] 공유 기능 수정

- src/App.tsx
- src/hooks/common/useHotjar.ts
- [https://github.com/Nexters/misik-web/issues/130](https://github.com/Nexters/misik-web/issues/130)
- hotjar 추가
> [Feat/#130] hotjar 추가

- src/pages/CreateReviewFailPage/CreateReviewFailPage.tsx
- src/pages/HomePage/HomePage.tsx
- src/pages/LoadingPage/LoadingPage.tsx
- src/pages/ReceiptEditPage/ReceiptEditPage.tsx
- src/pages/ReceiptInputPage/ReceiptInputPage.tsx
- src/pages/RecognitionFailPage/RecognitionFailPage.tsx
- src/pages/ReviewResultPage/ReviewResultPage.tsx
- src/pages/SelectStylePage/SelectStylePage.tsx
- src/pages/SelectTagPage/SelectTagPage.tsx
- src/types/global.d.ts
- src/utils/gtag.ts
- [https://github.com/Nexters/misik-web/issues/137](https://github.com/Nexters/misik-web/issues/137)
- GA 이벤트 추적용 버튼 id들 추가
> [Feat/#137] 구글 애널리틱스 버튼 이벤트 추적 태그 추가
